const data = {
  clothing: [
    {
      id: 0,
      type: "pant",
      variation: "long",
      color: "pink",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/longpant_pink.jpg",
    },
    {
      id: 1,
      type: "top",
      variation: "short",
      color: "black",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/black_top.jpeg",
    },
    {
      id: 2,
      type: "pant",
      variation: "long",
      color: "red",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/longpant_red.jpg",
    },
    {
      id: 3,
      type: "skirt",
      variation: "long",
      color: "black",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/longskirt_black.png",
    },
    {
      id: 4,
      type: "skirt",
      variation: "long",
      color: "green",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/longskirt_green.jpeg",
    },
    {
      id: 5,
      type: "skirt",
      variation: "long",
      color: "jeans",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/longskirt_jeans.jpeg",
    },
    {
      id: 6,
      type: "pant",
      variation: "short",
      color: "grey",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/shortpant_grey.jpeg",
    },
    {
      id: 7,
      type: "pant",
      variation: "short",
      color: "jeans",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/shortpant_jeans.jpeg",
    },
    {
      id: 8,
      type: "pant",
      variation: "short",
      color: "smoke",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/shortpant_smoke.jpeg",
    },
    {
      id: 9,
      type: "pant",
      variation: "short",
      color: "white",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/shortpant_white.jpeg",
    },
    {
      id: 10,
      type: "pant",
      variation: "short",
      color: "white",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/shortpant_white1.jpeg",
    },
    {
      id: 11,
      type: "pant",
      variation: "short",
      color: "kaki",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/shortpant_kaki.jpeg",
    },
    {
      id: 12,
      type: "skirt",
      variation: "short",
      color: "black",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/skirt_black.jpeg",
    },
    {
      id: 13,
      type: "skirt",
      variation: "short",
      color: "jeans",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/skirt_jeans_vintage.jpeg",
    },
    {
      id: 14,
      type: "skirt",
      variation: "short",
      color: "jeans",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/skirt_jeans.png",
    },
    {
      id: 15,
      type: "skirt",
      variation: "short",
      color: "pink",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/skirt_pink.jpeg",
    },
    {
      id: 16,
      type: "skirt",
      variation: "short",
      color: "white",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/skirt_white1.png",
    },
    {
      id: 17,
      type: "shirt",
      variation: "beach",
      color: "blue",
      size: "15-20",
      gender: "boy",
      price: 8,
      img: "data/image_data/clothing/beach_babyboy.jpeg",
    },
    {
      id: 18,
      type: "shirt",
      variation: "dark",
      color: "blue",
      size: "60-80",
      gender: "men",
      price: 8,
      img: "data/image_data/clothing/darkblue_menshirt.jpeg",
    },
    {
      id: 19,
      type: "pant",
      variation: "jeans",
      color: "black",
      size: "60-80",
      gender: "men",
      price: 8,
      img: "data/image_data/clothing/blackjean_men.jpeg",
    },
    {
      id: 20,
      type: "pant",
      variation: "jeans",
      color: "blue",
      size: "60-80",
      gender: "men",
      price: 8,
      img: "data/image_data/clothing/bluejean_men.jpg",
    },
    {
      id: 21,
      type: "dress",
      variation: "long",
      color: "pink",
      size: "20-30",
      gender: "girl",
      price: 8,
      img: "data/image_data/clothing/pink_babygirl.jpeg",
    },
    {
      id: 22,
      type: "dress",
      variation: "long",
      color: "white",
      size: "20-30",
      gender: "girl",
      price: 8,
      img: "data/image_data/clothing/white_babygirl.jpeg",
    },
    {
      id: 23,
      type: "top",
      variation: "short",
      color: "brown",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/brown_top.png",
    },
    {
      id: 24,
      type: "top",
      variation: "sexy",
      color: "pink",
      size: "40-60",
      gender: "women",
      price: 8,
      img: "data/image_data/clothing/palepink_top.png",
    },
  ],
};

export default data;
